delete from QuesBank
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'文学', N'老舍原名？', N'舒庆春', N'周作人', N'董仲舒', N'周树人', N'A')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'体育类', N'奥运会游泳比赛池中设有多少泳道?', N'6', N'8', N'7', N'10', N'B')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'影视', N'下列哪一部作品不是由桐华写的？', N'《步步惊心》', N'《大漠谣》 ', N'《云中歌》', N'《微微一笑很倾城》', N'D')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'音乐', N'以下哪首歌不是周杰伦演唱?', N'阳光宅男', N'路小雨', N'淘汰 ', N'彩虹', N'C')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'人文', N'下列诗句中，与生命现象没有关系的是', N'春眠不觉晓', N'处处闻啼鸟', N'夜来风雨声', N'花落知多少', N'C')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'常识', N'普通U盘的容量级别为多少？', N'KB', N'HB', N'GB', N'TB', N'C')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'文学', N'下列作品中哪一部不是金庸的？', N'《天龙八部》', N'《绝代双骄》', N'《白马啸西风》', N'《倚天屠龙剑》', N'B')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'常识', N'以下哪种菜系不属于中国八大菜系之列?', N'浙菜', N'鄂菜 ', N'闽菜', N'徽菜', N'B')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'音乐', N'六弦琴指的是什么乐器？', N'小提琴', N'大提琴', N'吉他', N'竖琴', N'C')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'自然', N'成都水稻一年几熟？', N'一年两熟 ', N'一年三熟', N'一年一熟', N'两年三熟', N'A')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'体育类', N'姚明在美国休斯敦火箭队效力时穿几号球衣？', N'11', N'12', N'13', N'14', N'A')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'体育类', N'刘翔在6月2日钻石联赛尤金站比赛夺冠成绩是多少？', N'12秒87', N'12秒88', N'12秒89', N'12秒90', N'A')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'科技类', N'光华园软件园页面的主色调是？', N'橙白', N'橙黑', N'蓝白', N'黑白', N'C')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'科技类', N'苹果新品发布会上的黑科技机器人的名字？', N'Liam ', N'Siam', N'Lien', N'Sien', N'A')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'音乐类', N'古典歌曲《满江红》的词作者是', N'文天祥', N'岳飞 ', N'屈原', N'曹操', N'B')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'常识', N'哪一种物品是最不稀缺的(   )?', N'医生', N'苹果', N'铁钻石', N'空气', N'D')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'网络', N'百度贴吧中“帝吧”指', N'扒皮吧', N'李毅吧', N'皇帝吧', N'春节联欢晚会吧', N'B')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'常识', N'奥运五环中黄色的一环代表哪个州？ ', N'欧洲', N'非洲', N'亚洲', N'北美洲', N'A')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'体育', N'世界著名羽毛球运动员李宗伟来自哪个国家？', N'马来西亚', N'印度', N'中国台湾', N'越南', N'A')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'影视', N'《琅琊榜》飞流扮演者？', N'吴亦凡', N'胡歌', N'霍建华', N'吴磊', N'D')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'影视', N'电影《我的少女时代》女主角林真心的偶像是？', N'刘德华', N'张学友', N'言承旭', N'张国荣', N'A')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'体育', N'乒乓球届的大魔王是？', N'王楠', N'张怡宁', N'马林', N'张继科', N'B')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'影视', N'下列哪部电影白百何未参演？（  ）', N'滚蛋吧，肿瘤君', N'失恋三十三天', N'被偷走的那五年', N'破风', N'D')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'常识', N'五味不包括（  ）', N'甘', N'咸', N'酸', N'辣', N'A')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'西财校园', N'西财图书馆最晚关灯的是几楼？', N'2', N'3', N'4', N'5', N'C')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'西财校园', N'济民广场有几根柱子？', N'7', N'8', N'9', N'10', N'B')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'科技', N'英雄联盟在中国由哪家公司代理', N'百度', N'腾讯', N'网易', N'盛大', N'B')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'科技', N'苹果公司没有发布过以下哪一款手机：', N'iPhone 3Gs', N'iPhone 4c', N'iPhone 5c', N'iPhone SE', N'B')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'科技', N'苹果公司现任CEO叫做', N'斯皮尔伯格', N'史蒂芬·乔布斯', N'蒂姆·库克', N'比尔盖茨 ', N'C')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'科技', N'号称掌握核心科技的家电公司是哪家', N'海尔', N'美的', N'格力', N'长虹', N'C')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'科技', N'以下哪个软件不是修图软件：', N'PS', N'AE', N'美图秀秀', N'光影魔术手', N'B')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'历史', N'战国时期，执六国相印的是', N'张仪', N'乐毅', N'苏秦', N'吕不韦', N'C')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'历史', N'明朝在位时间最长的皇帝是哪位？', N'万历帝（朱翊钧）', N'明太祖（朱元璋）', N'明成祖（朱棣）', N'明光宗（朱常洛）', N'A')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'历史', N'“四羊方尊”是哪个朝代的文物', N'周', N'元', N'商', N'夏', N'C')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'音乐', N'管弦乐队(Orchestra)起源于哪里?', N'亚 洲', N'欧洲', N'拉丁美洲', N'大洋洲', N'B')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'影视', N'第88届奥斯卡影帝是？', N'莱昂纳多', N'马特·达蒙', N'迈克尔·法斯宾德', N'埃迪·雷德梅因', N'A')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'自然', N'下列哪一天地球离太阳最近？', N'春分', N'夏至', N'秋分 ', N'冬至', N'D')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'科技', N'chrome浏览器是哪一个公司研发的?', N'腾讯', N'谷歌', N'雅虎', N'微软', N'B')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'自然', N'我国长江沿岸的“三大火炉”没有', N'重庆', N'吐鲁番', N'武汉', N'南京', N'B')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'体育', N'奥运会游泳比赛池中设有多少泳道', N'6', N'8', N'7', N'10', N'B')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'体育', N'乔丹球衣号码', N'21', N'22', N'23', N'24', N'C')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'体育', N'被称为“世界第一运动”的是什么运动?', N'足球', N'篮球', N'排球', N'羽毛球', N'A')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'体育', N'体育运动篮球最早起源于', N'美国', N'英国', N'法国', N'中国', N'A')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'体育', N'我国被称为哪一类体育运动的体育王国?', N'羽毛球', N'乒乓球', N'排球', N'举重', N'B')
INSERT [dbo].[QuesBank] ([Class], [Ques], [OptionA], [OptionB], [OptionC], [OptionD], [Answer]) VALUES (N'体育', N'乒乓球起源于哪个国家?', N'美国', N'英国', N'法国', N'中国', N'B')